version: 0.0
os: linux

files:
  - source: files/quim.txt
  destination: /tmp/

hooks:
  BeforeInstall:
    - location: scripts/stop-ignition.sh
  AfterInstall:
    - location: scripts/install-ignition.sh
    - location: scripts/start-ignition.sh